apiVersion: v1
kind: Pod
metadata:
  name: "test-gpu-{{testid}}-{{node}}"
  labels:
{% filter indent(4) %}
{% include "common_labels.yaml" %}
{% endfilter %}
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: "{{node}}"
  containers:
  - name: vectoradd
    image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
    resources:
      limits:
        nvidia.com/gpu: 1
  tolerations:
    - key: "nvidia.com/gpu.product"
      operator: "Exists"
      effect: "NoSchedule"

