apiVersion: batch/v1
kind: Job
metadata:
  name: "test-job-{{testid}}"
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: "{{ testimage }}"
        imagePullPolicy: Always
        name: test-container
        command:
          - curl
          - -Ssf
          - -o
          - /dev/null
          - -w
          - '%{http_code}\n'
          - "{{ url|default('https://www.goiogle.com') }}"
