apiVersion: v1
kind: Pod
metadata:
  labels:
{% filter indent(4) %}
{% include "common_labels.yaml" %}
{% endfilter %}
  name: "test-pod-{{testid}}"
spec:
  containers:
  - image: "{{ testimage }}"
    imagePullPolicy: Always
    name: test-container
    ports:
    - containerPort: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
{% filter indent(4) %}
{% include "common_labels.yaml" %}
{% endfilter %}
  name: "test-pod-{{testid}}"
spec:
  ports:
  - port: 8080
    targetPort: http
  selector:
{% filter indent(4) %}
{% include "common_labels.yaml" %}
{% endfilter %}
