apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod_with_service
  name: "test-pod-{{testid}}"
spec:
  containers:
  - image: "{{ testimage }}"
    imagePullPolicy: Always
    name: test-container
    ports:
    - containerPort: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pod_with_service
  name: "test-pod-{{testid}}"
spec:
  ports:
  - port: 8080
    targetPort: http
  selector:
    testid: "{{ testid }}"
    app: pod_with_service
