apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume-{{testid}}
  labels:
{% filter indent(4) %}
{% include "common_labels.yaml" %}
{% endfilter %}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
