apiVersion: v1
kind: Pod
metadata:
  name: "test-pod-{{testid}}-{{node}}"
  labels:
    test: pvc-per-node
spec:
  nodeSelector:
    kubernetes.io/hostname: "{{node}}"
  containers:
  - image: "{{ testimage }}"
    imagePullPolicy: Always
    name: test-container
    volumeMounts:
    - mountPath: /mnt
      name: test-volume
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: "test-volume-{{testid}}-{{node}}"
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu.product
    operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "test-volume-{{testid}}-{{node}}"
  labels:
    test: pvc-per-node
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
