apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "vault-check-{{ testid }}"
  labels:
{% filter indent(4) %}
{% include "common_labels.yaml" %}
{% endfilter %}
spec:
  selector:
    matchLabels:
{% filter indent(6) %}
{% include "common_labels.yaml" %}
{% endfilter %}
  template:
    metadata:
      labels:
{% filter indent(8) %}
{% include "common_labels.yaml" %}
{% endfilter %}
    spec:
      containers:
      - name: check
        image: "{{ testimage }}"
        readinessProbe:
          exec:
            command:
            - curl
            - -SsfL
            - "{{ url }}"
          initialDelaySeconds: 1
          periodSeconds: 5
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu.product
        operator: Exists
